---
- name: Add users from usernames.txt
  hosts: all_linux
  become: true
  vars:
    user_file: "/root/usernames.txt"
  tasks:
    - name: Read usernames and passwords from file
      ansible.builtin.slurp:
        src: "{{ user_file }}"
      register: user_file_content

    - name: Decode the usernames file
      set_fact:
        decoded_content: "{{ user_file_content['content'] | b64decode }}"

    - name: Convert decoded content into a list of users
      set_fact:
        users_list: "{{ decoded_content.splitlines() | map('regex_replace', '^([^,]+),(.+)$', '\\1:\\2') | list }}"

    - name: Create users with passwords from usernames.txt
      ansible.builtin.user:
        name: "{{ item.split(':')[0] }}"
        password: "{{ 'password' | password_hash('sha512') }}"
        state: present
      loop: "{{ users_list }}"
      when: item != 'user:password'
