---
- name: Install DNS and configure DNS records
  hosts: windows
  become: yes
  tasks:
    
    - name: Install DNS feature
      ansible.windows.win_feature:
        name: DNS
        state: present
      register: dns_installed

    - name: Ensure DNS service is running
      ansible.windows.win_service:
        name: DNS
        start_mode: auto
        state: started
      when: dns_installed.changed

    - name: Add DNS record awu.lks2024.id -> 10.17.8.45
      ansible.windows.win_dns_record:
        zone: "lks2024.id"
        name: "awu"
        type: "A"
        value: "10.17.8.45"
        state: present
      register: dns_record_added

    - name: Verify the DNS record creation
      ansible.windows.win_shell: nslookup awu.lks2024.id
      register: nslookup_result
      changed_when: false

    - debug:
        msg: "DNS record successfully added and verified: {{ nslookup_result.stdout }}"

  handlers:
    - name: Remove DNS record awu.lks2024.id after testing
      ansible.windows.win_dns_record:
        zone: "lks2024.id"
        name: "awu"
        type: "A"
        value: "10.17.8.45"
        state: absent
      when: dns_record_added.changed
